config_message: "Hello From user-service in test profile"
token:
  secret: '{cipher}AQB1qX6aNkPjOXznxyeHKntOO+OkmZ9reuAqqBZrQnuUd8hDkxipV8HMF9WO424SK8i8q3J5P3/YcNt3cn/NR+FkpoSH9IBleHWyE9ndbV1tpkYHr3bQe+8OGCV5wW8aJwXvrOiyEcL7mXuGTJqKCvvPxpW92fsXsudTZxeitVYdSC1gCW0Uh7DY9jFFMEte5SxzZGhxF+WItzc6VASj+/l0jhDmJeNnHizKCwbLEr3NLFmFgiE6uyvBav5l43KnxhBTGUHdbakftfqQ0mNYACZWMnU+ULCvK2U9IwG21yv9p9B6xZULbTGRFyYDxL6n4nIgFpkiClvnJkMx1gIzeijWh8KgqEi+zsHXzVD+XXVM226IVAS9ohjTMMGM26MVSns='
spring:
  datasource:
    password: '{cipher}AQCHiX825X5ugjKJZ8+5gQ4ccplT7CSWt3XTab7DvzfWPma/PRQjuJWnzL9Ub+KV4XtfKryVZntiyqXCe/0f5pF3hAT0wJEznKByE4qm/BMYQmG/+kTtA0qvJ4JFWWC+ftH7TImSyLOo8fFKHPAFKEECOnPcTaoNxIjs2pmui7LCpeUiPuBFmbAAKipJMisD3NfMWKgjKfcUcfiJLrbMPa74XeehahqwwMpr9XC/yjJzbf+v7phk4g7FTsCpFcDQUyb9Nv6QY4oRRRNFGqhkdN61pg0iOEB4Hh9mqJHDW1ondfT8Y+KNLGfRCx+amVKwgnZZIIUsOrIzuJ7eO/BRVaGmYa4Xe/3o9Wy8Wvr1mKAllJuUPVCSwOPw0kXHiuTeFu4='
  
